### ISSUE TITLE
The gradients for updating actors 2

### ISSUE THREAD

**Issue by namidairo777** [agakshat/maddpg#4]
It seems line 62 `action_dims_done = 0`  should be in between line 49 and line 60 
instead of in line 61 `for i in range(env.n):` loop,  
which could lead to getting correct action gradients from centralized critic.
(#2 also mentioned it)

**Comment by agakshat** [comment]
Thanks for bringing this to my notice! I've pushed the change.

**Comment by namidairo777** [comment]
In my opinion, when you are testing on "simple_tag" environment, you should run maddpg on adversary agents (predator) instead of all agents, and apply ddpg or other algorithm to good agents (prey).
This may help to get a cool result.
