### ISSUE TITLE
agents out of the box

### ISSUE THREAD

**Issue by hyren** [agakshat/maddpg#6]
1. Is it better if one rollout ends as long as any one agent runs out of the box?

2. The NaN problem also occurs to me.

**Comment by agakshat** [comment]
I did not understand your first question. Can you be more specific?
And please see #5 for your other point.

**Comment by hyren** [comment]
In your version, one rollout ends when all the agents run out of the box. I wonder whether it helps the training if one rollout ends when any single agent runs out of the box.

**Comment by agakshat** [comment]
Yeah, I did try that out as well but it was leading to the rollouts ending very quickly without any significant experience gained for the agents.

**Comment by hyren** [comment]
Yeah, that's true
