### ISSUE TITLE
Multiagent.py is missing

### ISSUE THREAD

**Issue by emanuelepesce** [agakshat/maddpg#7]
According to the readme:

> Go into the maddpg directory here and run python3 multiagent.py. Should run straight out of the box.

But there is no file named multiagent.py

**Comment by agakshat** [comment]
Yes, I renamed that to `training-code.py` to resolve a naming conflict. Seems I haven't updated the README yet. Thanks for pointing out the error

**Comment by emanuelepesce** [comment]
Thanks for your answer, I had noticed that.
